// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Whisparr3.Net.Client;
using Whisparr3.Net.Logging;
using Whisparr3.Net.Model;
using System.Diagnostics.CodeAnalysis;

namespace Whisparr3.Net.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IManualImportApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        ManualImportApiEvents Events { get; }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="manualImportReprocessResource"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateManualImportApiResponse"/>&gt;</returns>
        Task<ICreateManualImportApiResponse> CreateManualImportAsync(Option<List<ManualImportReprocessResource>> manualImportReprocessResource = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="manualImportReprocessResource"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateManualImportApiResponse"/>?&gt;</returns>
        Task<ICreateManualImportApiResponse?> CreateManualImportOrDefaultAsync(Option<List<ManualImportReprocessResource>> manualImportReprocessResource = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="folder"> (optional)</param>
        /// <param name="downloadId"> (optional)</param>
        /// <param name="movieId"> (optional)</param>
        /// <param name="filterExistingFiles"> (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListManualImportApiResponse"/>&gt;</returns>
        Task<IListManualImportApiResponse> ListManualImportAsync(Option<string> folder = default, Option<string> downloadId = default, Option<int> movieId = default, Option<bool> filterExistingFiles = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="folder"> (optional)</param>
        /// <param name="downloadId"> (optional)</param>
        /// <param name="movieId"> (optional)</param>
        /// <param name="filterExistingFiles"> (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListManualImportApiResponse"/>?&gt;</returns>
        Task<IListManualImportApiResponse?> ListManualImportOrDefaultAsync(Option<string> folder = default, Option<string> downloadId = default, Option<int> movieId = default, Option<bool> filterExistingFiles = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ICreateManualImportApiResponse"/>
    /// </summary>
    public interface ICreateManualImportApiResponse : Whisparr3.Net.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IListManualImportApiResponse"/>
    /// </summary>
    public interface IListManualImportApiResponse : Whisparr3.Net.Client.IApiResponse, IOk<List<ManualImportResource>?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class ManualImportApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCreateManualImport;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCreateManualImport;

        internal void ExecuteOnCreateManualImport(ManualImportApi.CreateManualImportApiResponse apiResponse)
        {
            OnCreateManualImport?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCreateManualImport(Exception exception)
        {
            OnErrorCreateManualImport?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnListManualImport;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorListManualImport;

        internal void ExecuteOnListManualImport(ManualImportApi.ListManualImportApiResponse apiResponse)
        {
            OnListManualImport?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorListManualImport(Exception exception)
        {
            OnErrorListManualImport?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class ManualImportApi : IManualImportApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<ManualImportApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public ManualImportApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ManualImportApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ManualImportApi(ILogger<ManualImportApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, ManualImportApiEvents manualImportApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = manualImportApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatCreateManualImport(Option<List<ManualImportReprocessResource>> manualImportReprocessResource);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="manualImportReprocessResource"></param>
        /// <returns></returns>
        private void ValidateCreateManualImport(Option<List<ManualImportReprocessResource>> manualImportReprocessResource)
        {
            if (manualImportReprocessResource.IsSet && manualImportReprocessResource.Value == null)
                throw new ArgumentNullException(nameof(manualImportReprocessResource));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="manualImportReprocessResource"></param>
        private void AfterCreateManualImportDefaultImplementation(ICreateManualImportApiResponse apiResponseLocalVar, Option<List<ManualImportReprocessResource>> manualImportReprocessResource)
        {
            bool suppressDefaultLog = false;
            AfterCreateManualImport(ref suppressDefaultLog, apiResponseLocalVar, manualImportReprocessResource);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="manualImportReprocessResource"></param>
        partial void AfterCreateManualImport(ref bool suppressDefaultLog, ICreateManualImportApiResponse apiResponseLocalVar, Option<List<ManualImportReprocessResource>> manualImportReprocessResource);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="manualImportReprocessResource"></param>
        private void OnErrorCreateManualImportDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<List<ManualImportReprocessResource>> manualImportReprocessResource)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCreateManualImport(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, manualImportReprocessResource);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="manualImportReprocessResource"></param>
        partial void OnErrorCreateManualImport(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<List<ManualImportReprocessResource>> manualImportReprocessResource);

        /// <summary>
        ///  
        /// </summary>
        /// <param name="manualImportReprocessResource"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateManualImportApiResponse"/>&gt;</returns>
        public async Task<ICreateManualImportApiResponse?> CreateManualImportOrDefaultAsync(Option<List<ManualImportReprocessResource>> manualImportReprocessResource = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CreateManualImportAsync(manualImportReprocessResource, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="manualImportReprocessResource"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateManualImportApiResponse"/>&gt;</returns>
        public async Task<ICreateManualImportApiResponse> CreateManualImportAsync(Option<List<ManualImportReprocessResource>> manualImportReprocessResource = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCreateManualImport(manualImportReprocessResource);

                FormatCreateManualImport(manualImportReprocessResource);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v3/manualimport"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v3/manualimport");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (manualImportReprocessResource.IsSet)
                    {
                      httpRequestMessageLocalVar.Content = (manualImportReprocessResource.Value as object) is Whisparr3.Net.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(manualImportReprocessResource.Value, _jsonSerializerOptions));
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("apikey", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);

                    apiKeyTokenLocalVar1.UseInQuery(httpRequestMessageLocalVar, uriBuilderLocalVar, parseQueryStringLocalVar);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();
                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Api-Key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        CreateManualImportApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v3/manualimport", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCreateManualImportDefaultImplementation(apiResponseLocalVar, manualImportReprocessResource);

                        Events.ExecuteOnCreateManualImport(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCreateManualImportDefaultImplementation(e, "/api/v3/manualimport", uriBuilderLocalVar.Path, manualImportReprocessResource);
                Events.ExecuteOnErrorCreateManualImport(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CreateManualImportApiResponse"/>
        /// </summary>
        public partial class CreateManualImportApiResponse : Whisparr3.Net.Client.ApiResponse, ICreateManualImportApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ManualImportApi> Logger { get; }

            /// <summary>
            /// The <see cref="CreateManualImportApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateManualImportApiResponse(ILogger<ManualImportApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CreateManualImportApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateManualImportApiResponse(ILogger<ManualImportApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatListManualImport(ref Option<string> folder, ref Option<string> downloadId, ref Option<int> movieId, ref Option<bool> filterExistingFiles);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="folder"></param>
        /// <param name="downloadId"></param>
        /// <returns></returns>
        private void ValidateListManualImport(Option<string> folder, Option<string> downloadId)
        {
            if (folder.IsSet && folder.Value == null)
                throw new ArgumentNullException(nameof(folder));

            if (downloadId.IsSet && downloadId.Value == null)
                throw new ArgumentNullException(nameof(downloadId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="folder"></param>
        /// <param name="downloadId"></param>
        /// <param name="movieId"></param>
        /// <param name="filterExistingFiles"></param>
        private void AfterListManualImportDefaultImplementation(IListManualImportApiResponse apiResponseLocalVar, Option<string> folder, Option<string> downloadId, Option<int> movieId, Option<bool> filterExistingFiles)
        {
            bool suppressDefaultLog = false;
            AfterListManualImport(ref suppressDefaultLog, apiResponseLocalVar, folder, downloadId, movieId, filterExistingFiles);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="folder"></param>
        /// <param name="downloadId"></param>
        /// <param name="movieId"></param>
        /// <param name="filterExistingFiles"></param>
        partial void AfterListManualImport(ref bool suppressDefaultLog, IListManualImportApiResponse apiResponseLocalVar, Option<string> folder, Option<string> downloadId, Option<int> movieId, Option<bool> filterExistingFiles);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="folder"></param>
        /// <param name="downloadId"></param>
        /// <param name="movieId"></param>
        /// <param name="filterExistingFiles"></param>
        private void OnErrorListManualImportDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> folder, Option<string> downloadId, Option<int> movieId, Option<bool> filterExistingFiles)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorListManualImport(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, folder, downloadId, movieId, filterExistingFiles);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="folder"></param>
        /// <param name="downloadId"></param>
        /// <param name="movieId"></param>
        /// <param name="filterExistingFiles"></param>
        partial void OnErrorListManualImport(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> folder, Option<string> downloadId, Option<int> movieId, Option<bool> filterExistingFiles);

        /// <summary>
        ///  
        /// </summary>
        /// <param name="folder"> (optional)</param>
        /// <param name="downloadId"> (optional)</param>
        /// <param name="movieId"> (optional)</param>
        /// <param name="filterExistingFiles"> (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListManualImportApiResponse"/>&gt;</returns>
        public async Task<IListManualImportApiResponse?> ListManualImportOrDefaultAsync(Option<string> folder = default, Option<string> downloadId = default, Option<int> movieId = default, Option<bool> filterExistingFiles = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ListManualImportAsync(folder, downloadId, movieId, filterExistingFiles, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="folder"> (optional)</param>
        /// <param name="downloadId"> (optional)</param>
        /// <param name="movieId"> (optional)</param>
        /// <param name="filterExistingFiles"> (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListManualImportApiResponse"/>&gt;</returns>
        public async Task<IListManualImportApiResponse> ListManualImportAsync(Option<string> folder = default, Option<string> downloadId = default, Option<int> movieId = default, Option<bool> filterExistingFiles = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateListManualImport(folder, downloadId);

                FormatListManualImport(ref folder, ref downloadId, ref movieId, ref filterExistingFiles);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v3/manualimport"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v3/manualimport");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (folder.IsSet)
                        parseQueryStringLocalVar["folder"] = ClientUtils.ParameterToString(folder.Value);

                    if (downloadId.IsSet)
                        parseQueryStringLocalVar["downloadId"] = ClientUtils.ParameterToString(downloadId.Value);

                    if (movieId.IsSet)
                        parseQueryStringLocalVar["movieId"] = ClientUtils.ParameterToString(movieId.Value);

                    if (filterExistingFiles.IsSet)
                        parseQueryStringLocalVar["filterExistingFiles"] = ClientUtils.ParameterToString(filterExistingFiles.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("apikey", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);

                    apiKeyTokenLocalVar1.UseInQuery(httpRequestMessageLocalVar, uriBuilderLocalVar, parseQueryStringLocalVar);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();
                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Api-Key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ListManualImportApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v3/manualimport", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterListManualImportDefaultImplementation(apiResponseLocalVar, folder, downloadId, movieId, filterExistingFiles);

                        Events.ExecuteOnListManualImport(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorListManualImportDefaultImplementation(e, "/api/v3/manualimport", uriBuilderLocalVar.Path, folder, downloadId, movieId, filterExistingFiles);
                Events.ExecuteOnErrorListManualImport(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ListManualImportApiResponse"/>
        /// </summary>
        public partial class ListManualImportApiResponse : Whisparr3.Net.Client.ApiResponse, IListManualImportApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ManualImportApi> Logger { get; }

            /// <summary>
            /// The <see cref="ListManualImportApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListManualImportApiResponse(ILogger<ManualImportApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ListManualImportApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListManualImportApiResponse(ILogger<ManualImportApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public List<ManualImportResource>? Ok()
            {
                bool suppressDefault = false;
                List<ManualImportResource>? result = null;
                OnOk(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultOk();
                return result;
            }

            private List<ManualImportResource>? DefaultOk()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<List<ManualImportResource>>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnOk(ref bool suppressDefault, ref List<ManualImportResource>? result);

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out List<ManualImportResource>? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
