// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr3.Net.Client;

namespace Whisparr3.Net.Model
{
    /// <summary>
    /// Defines CommandResult
    /// </summary>
    public enum CommandResult
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        Unknown,

        /// <summary>
        /// Enum Successful for value: successful
        /// </summary>
        Successful,

        /// <summary>
        /// Enum Unsuccessful for value: unsuccessful
        /// </summary>
        Unsuccessful
    }

    /// <summary>
    /// Converts <see cref="CommandResult"/> to and from the JSON value
    /// </summary>
    public static class CommandResultValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="CommandResult"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CommandResult FromString(string value)
        {
            if (value.Equals("unknown"))
                return CommandResult.Unknown;

            if (value.Equals("successful"))
                return CommandResult.Successful;

            if (value.Equals("unsuccessful"))
                return CommandResult.Unsuccessful;

            throw new NotImplementedException($"Could not convert value to type CommandResult: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="CommandResult"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CommandResult? FromStringOrDefault(string value)
        {
            if (value.Equals("unknown"))
                return CommandResult.Unknown;

            if (value.Equals("successful"))
                return CommandResult.Successful;

            if (value.Equals("unsuccessful"))
                return CommandResult.Unsuccessful;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CommandResult"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(CommandResult value)
        {
            if (value == CommandResult.Unknown)
                return "unknown";

            if (value == CommandResult.Successful)
                return "successful";

            if (value == CommandResult.Unsuccessful)
                return "unsuccessful";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CommandResult"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class CommandResultJsonConverter : JsonConverter<CommandResult>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CommandResult Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CommandResult? result = rawValue == null
                ? null
                : CommandResultValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CommandResult to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="commandResult"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CommandResult commandResult, JsonSerializerOptions options)
        {
            writer.WriteStringValue(CommandResultValueConverter.ToJsonValue(commandResult).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CommandResult"/>
    /// </summary>
    public class CommandResultNullableJsonConverter : JsonConverter<CommandResult?>
    {
        /// <summary>
        /// Returns a CommandResult from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CommandResult? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            CommandResult? result = rawValue == null
                ? null
                : CommandResultValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CommandResult to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="commandResult"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CommandResult? commandResult, JsonSerializerOptions options)
        {
            if (commandResult.HasValue)
                writer.WriteStringValue(CommandResultValueConverter.ToJsonValue(commandResult.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }
}
