// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr3.Net.Client;

namespace Whisparr3.Net.Model
{
    /// <summary>
    /// DelayProfileResource
    /// </summary>
    public partial class DelayProfileResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DelayProfileResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="enableUsenet">enableUsenet</param>
        /// <param name="enableTorrent">enableTorrent</param>
        /// <param name="preferredProtocol">preferredProtocol</param>
        /// <param name="usenetDelay">usenetDelay</param>
        /// <param name="torrentDelay">torrentDelay</param>
        /// <param name="bypassIfHighestQuality">bypassIfHighestQuality</param>
        /// <param name="bypassIfAboveCustomFormatScore">bypassIfAboveCustomFormatScore</param>
        /// <param name="minimumCustomFormatScore">minimumCustomFormatScore</param>
        /// <param name="order">order</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public DelayProfileResource(Option<int?> id = default, Option<bool?> enableUsenet = default, Option<bool?> enableTorrent = default, Option<DownloadProtocol?> preferredProtocol = default, Option<int?> usenetDelay = default, Option<int?> torrentDelay = default, Option<bool?> bypassIfHighestQuality = default, Option<bool?> bypassIfAboveCustomFormatScore = default, Option<int?> minimumCustomFormatScore = default, Option<int?> order = default, Option<List<int>?> tags = default)
        {
            IdOption = id;
            EnableUsenetOption = enableUsenet;
            EnableTorrentOption = enableTorrent;
            PreferredProtocolOption = preferredProtocol;
            UsenetDelayOption = usenetDelay;
            TorrentDelayOption = torrentDelay;
            BypassIfHighestQualityOption = bypassIfHighestQuality;
            BypassIfAboveCustomFormatScoreOption = bypassIfAboveCustomFormatScore;
            MinimumCustomFormatScoreOption = minimumCustomFormatScore;
            OrderOption = order;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of PreferredProtocol
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DownloadProtocol?> PreferredProtocolOption { get; private set; }

        /// <summary>
        /// Gets or Sets PreferredProtocol
        /// </summary>
        [JsonPropertyName("preferredProtocol")]
        public DownloadProtocol? PreferredProtocol { get { return this.PreferredProtocolOption.Value; } set { this.PreferredProtocolOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableUsenet
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableUsenetOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableUsenet
        /// </summary>
        [JsonPropertyName("enableUsenet")]
        public bool? EnableUsenet { get { return this.EnableUsenetOption.Value; } set { this.EnableUsenetOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableTorrent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableTorrentOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableTorrent
        /// </summary>
        [JsonPropertyName("enableTorrent")]
        public bool? EnableTorrent { get { return this.EnableTorrentOption.Value; } set { this.EnableTorrentOption = new(value); } }

        /// <summary>
        /// Used to track the state of UsenetDelay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> UsenetDelayOption { get; private set; }

        /// <summary>
        /// Gets or Sets UsenetDelay
        /// </summary>
        [JsonPropertyName("usenetDelay")]
        public int? UsenetDelay { get { return this.UsenetDelayOption.Value; } set { this.UsenetDelayOption = new(value); } }

        /// <summary>
        /// Used to track the state of TorrentDelay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TorrentDelayOption { get; private set; }

        /// <summary>
        /// Gets or Sets TorrentDelay
        /// </summary>
        [JsonPropertyName("torrentDelay")]
        public int? TorrentDelay { get { return this.TorrentDelayOption.Value; } set { this.TorrentDelayOption = new(value); } }

        /// <summary>
        /// Used to track the state of BypassIfHighestQuality
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> BypassIfHighestQualityOption { get; private set; }

        /// <summary>
        /// Gets or Sets BypassIfHighestQuality
        /// </summary>
        [JsonPropertyName("bypassIfHighestQuality")]
        public bool? BypassIfHighestQuality { get { return this.BypassIfHighestQualityOption.Value; } set { this.BypassIfHighestQualityOption = new(value); } }

        /// <summary>
        /// Used to track the state of BypassIfAboveCustomFormatScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> BypassIfAboveCustomFormatScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets BypassIfAboveCustomFormatScore
        /// </summary>
        [JsonPropertyName("bypassIfAboveCustomFormatScore")]
        public bool? BypassIfAboveCustomFormatScore { get { return this.BypassIfAboveCustomFormatScoreOption.Value; } set { this.BypassIfAboveCustomFormatScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of MinimumCustomFormatScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MinimumCustomFormatScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets MinimumCustomFormatScore
        /// </summary>
        [JsonPropertyName("minimumCustomFormatScore")]
        public int? MinimumCustomFormatScore { get { return this.MinimumCustomFormatScoreOption.Value; } set { this.MinimumCustomFormatScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of Order
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OrderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [JsonPropertyName("order")]
        public int? Order { get { return this.OrderOption.Value; } set { this.OrderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<int>? Tags { get { return this.TagsOption.Value; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DelayProfileResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  EnableUsenet: ").Append(EnableUsenet).Append("\n");
            sb.Append("  EnableTorrent: ").Append(EnableTorrent).Append("\n");
            sb.Append("  PreferredProtocol: ").Append(PreferredProtocol).Append("\n");
            sb.Append("  UsenetDelay: ").Append(UsenetDelay).Append("\n");
            sb.Append("  TorrentDelay: ").Append(TorrentDelay).Append("\n");
            sb.Append("  BypassIfHighestQuality: ").Append(BypassIfHighestQuality).Append("\n");
            sb.Append("  BypassIfAboveCustomFormatScore: ").Append(BypassIfAboveCustomFormatScore).Append("\n");
            sb.Append("  MinimumCustomFormatScore: ").Append(MinimumCustomFormatScore).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DelayProfileResource" />
    /// </summary>
    public partial class DelayProfileResourceJsonConverter : JsonConverter<DelayProfileResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DelayProfileResourceJsonConverter" /> class.
        /// </summary>
        public DelayProfileResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DelayProfileResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DelayProfileResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<bool?> enableUsenet = default;
            Option<bool?> enableTorrent = default;
            Option<DownloadProtocol?> preferredProtocol = default;
            Option<int?> usenetDelay = default;
            Option<int?> torrentDelay = default;
            Option<bool?> bypassIfHighestQuality = default;
            Option<bool?> bypassIfAboveCustomFormatScore = default;
            Option<int?> minimumCustomFormatScore = default;
            Option<int?> order = default;
            Option<List<int>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "enableUsenet":
                            enableUsenet = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "enableTorrent":
                            enableTorrent = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "preferredProtocol":
                            preferredProtocol = new Option<DownloadProtocol?>(JsonSerializer.Deserialize<DownloadProtocol?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "usenetDelay":
                            usenetDelay = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "torrentDelay":
                            torrentDelay = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bypassIfHighestQuality":
                            bypassIfHighestQuality = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "bypassIfAboveCustomFormatScore":
                            bypassIfAboveCustomFormatScore = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "minimumCustomFormatScore":
                            minimumCustomFormatScore = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "order":
                            order = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "tags":
                            tags = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class DelayProfileResource.");

            if (enableUsenet.IsSet && enableUsenet.Value == null)
                throw new ArgumentNullException(nameof(enableUsenet), "Property is not nullable for class DelayProfileResource.");

            if (enableTorrent.IsSet && enableTorrent.Value == null)
                throw new ArgumentNullException(nameof(enableTorrent), "Property is not nullable for class DelayProfileResource.");

            if (preferredProtocol.IsSet && preferredProtocol.Value == null)
                throw new ArgumentNullException(nameof(preferredProtocol), "Property is not nullable for class DelayProfileResource.");

            if (usenetDelay.IsSet && usenetDelay.Value == null)
                throw new ArgumentNullException(nameof(usenetDelay), "Property is not nullable for class DelayProfileResource.");

            if (torrentDelay.IsSet && torrentDelay.Value == null)
                throw new ArgumentNullException(nameof(torrentDelay), "Property is not nullable for class DelayProfileResource.");

            if (bypassIfHighestQuality.IsSet && bypassIfHighestQuality.Value == null)
                throw new ArgumentNullException(nameof(bypassIfHighestQuality), "Property is not nullable for class DelayProfileResource.");

            if (bypassIfAboveCustomFormatScore.IsSet && bypassIfAboveCustomFormatScore.Value == null)
                throw new ArgumentNullException(nameof(bypassIfAboveCustomFormatScore), "Property is not nullable for class DelayProfileResource.");

            if (minimumCustomFormatScore.IsSet && minimumCustomFormatScore.Value == null)
                throw new ArgumentNullException(nameof(minimumCustomFormatScore), "Property is not nullable for class DelayProfileResource.");

            if (order.IsSet && order.Value == null)
                throw new ArgumentNullException(nameof(order), "Property is not nullable for class DelayProfileResource.");

            return new DelayProfileResource(id, enableUsenet, enableTorrent, preferredProtocol, usenetDelay, torrentDelay, bypassIfHighestQuality, bypassIfAboveCustomFormatScore, minimumCustomFormatScore, order, tags);
        }

        /// <summary>
        /// Serializes a <see cref="DelayProfileResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="delayProfileResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DelayProfileResource delayProfileResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, delayProfileResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DelayProfileResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="delayProfileResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DelayProfileResource delayProfileResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (delayProfileResource.IdOption.IsSet)
                writer.WriteNumber("id", delayProfileResource.IdOption.Value!.Value);

            if (delayProfileResource.EnableUsenetOption.IsSet)
                writer.WriteBoolean("enableUsenet", delayProfileResource.EnableUsenetOption.Value!.Value);

            if (delayProfileResource.EnableTorrentOption.IsSet)
                writer.WriteBoolean("enableTorrent", delayProfileResource.EnableTorrentOption.Value!.Value);

            if (delayProfileResource.PreferredProtocolOption.IsSet)
            {
                var preferredProtocolRawValue = DownloadProtocolValueConverter.ToJsonValue(delayProfileResource.PreferredProtocol!.Value);
                writer.WriteString("preferredProtocol", preferredProtocolRawValue);
            }
            if (delayProfileResource.UsenetDelayOption.IsSet)
                writer.WriteNumber("usenetDelay", delayProfileResource.UsenetDelayOption.Value!.Value);

            if (delayProfileResource.TorrentDelayOption.IsSet)
                writer.WriteNumber("torrentDelay", delayProfileResource.TorrentDelayOption.Value!.Value);

            if (delayProfileResource.BypassIfHighestQualityOption.IsSet)
                writer.WriteBoolean("bypassIfHighestQuality", delayProfileResource.BypassIfHighestQualityOption.Value!.Value);

            if (delayProfileResource.BypassIfAboveCustomFormatScoreOption.IsSet)
                writer.WriteBoolean("bypassIfAboveCustomFormatScore", delayProfileResource.BypassIfAboveCustomFormatScoreOption.Value!.Value);

            if (delayProfileResource.MinimumCustomFormatScoreOption.IsSet)
                writer.WriteNumber("minimumCustomFormatScore", delayProfileResource.MinimumCustomFormatScoreOption.Value!.Value);

            if (delayProfileResource.OrderOption.IsSet)
                writer.WriteNumber("order", delayProfileResource.OrderOption.Value!.Value);

            if (delayProfileResource.TagsOption.IsSet)
                if (delayProfileResource.TagsOption.Value != null)
                {
                    writer.WritePropertyName("tags");
                    JsonSerializer.Serialize(writer, delayProfileResource.Tags, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("tags");
        }
    }
}
