// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr3.Net.Client;

namespace Whisparr3.Net.Model
{
    /// <summary>
    /// NotificationResource
    /// </summary>
    public partial class NotificationResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="fields">fields</param>
        /// <param name="implementationName">implementationName</param>
        /// <param name="implementation">implementation</param>
        /// <param name="configContract">configContract</param>
        /// <param name="infoLink">infoLink</param>
        /// <param name="message">message</param>
        /// <param name="tags">tags</param>
        /// <param name="presets">presets</param>
        /// <param name="link">link</param>
        /// <param name="onGrab">onGrab</param>
        /// <param name="onDownload">onDownload</param>
        /// <param name="onUpgrade">onUpgrade</param>
        /// <param name="onRename">onRename</param>
        /// <param name="onMovieAdded">onMovieAdded</param>
        /// <param name="onMovieDelete">onMovieDelete</param>
        /// <param name="onMovieFileDelete">onMovieFileDelete</param>
        /// <param name="onMovieFileDeleteForUpgrade">onMovieFileDeleteForUpgrade</param>
        /// <param name="onHealthIssue">onHealthIssue</param>
        /// <param name="includeHealthWarnings">includeHealthWarnings</param>
        /// <param name="onHealthRestored">onHealthRestored</param>
        /// <param name="onApplicationUpdate">onApplicationUpdate</param>
        /// <param name="onManualInteractionRequired">onManualInteractionRequired</param>
        /// <param name="supportsOnGrab">supportsOnGrab</param>
        /// <param name="supportsOnDownload">supportsOnDownload</param>
        /// <param name="supportsOnUpgrade">supportsOnUpgrade</param>
        /// <param name="supportsOnRename">supportsOnRename</param>
        /// <param name="supportsOnMovieAdded">supportsOnMovieAdded</param>
        /// <param name="supportsOnMovieDelete">supportsOnMovieDelete</param>
        /// <param name="supportsOnMovieFileDelete">supportsOnMovieFileDelete</param>
        /// <param name="supportsOnMovieFileDeleteForUpgrade">supportsOnMovieFileDeleteForUpgrade</param>
        /// <param name="supportsOnHealthIssue">supportsOnHealthIssue</param>
        /// <param name="supportsOnHealthRestored">supportsOnHealthRestored</param>
        /// <param name="supportsOnApplicationUpdate">supportsOnApplicationUpdate</param>
        /// <param name="supportsOnManualInteractionRequired">supportsOnManualInteractionRequired</param>
        /// <param name="testCommand">testCommand</param>
        [JsonConstructor]
        public NotificationResource(Option<int?> id = default, Option<string?> name = default, Option<List<Field>?> fields = default, Option<string?> implementationName = default, Option<string?> implementation = default, Option<string?> configContract = default, Option<string?> infoLink = default, Option<ProviderMessage?> message = default, Option<List<int>?> tags = default, Option<List<NotificationResource>?> presets = default, Option<string?> link = default, Option<bool?> onGrab = default, Option<bool?> onDownload = default, Option<bool?> onUpgrade = default, Option<bool?> onRename = default, Option<bool?> onMovieAdded = default, Option<bool?> onMovieDelete = default, Option<bool?> onMovieFileDelete = default, Option<bool?> onMovieFileDeleteForUpgrade = default, Option<bool?> onHealthIssue = default, Option<bool?> includeHealthWarnings = default, Option<bool?> onHealthRestored = default, Option<bool?> onApplicationUpdate = default, Option<bool?> onManualInteractionRequired = default, Option<bool?> supportsOnGrab = default, Option<bool?> supportsOnDownload = default, Option<bool?> supportsOnUpgrade = default, Option<bool?> supportsOnRename = default, Option<bool?> supportsOnMovieAdded = default, Option<bool?> supportsOnMovieDelete = default, Option<bool?> supportsOnMovieFileDelete = default, Option<bool?> supportsOnMovieFileDeleteForUpgrade = default, Option<bool?> supportsOnHealthIssue = default, Option<bool?> supportsOnHealthRestored = default, Option<bool?> supportsOnApplicationUpdate = default, Option<bool?> supportsOnManualInteractionRequired = default, Option<string?> testCommand = default)
        {
            IdOption = id;
            NameOption = name;
            FieldsOption = fields;
            ImplementationNameOption = implementationName;
            ImplementationOption = implementation;
            ConfigContractOption = configContract;
            InfoLinkOption = infoLink;
            MessageOption = message;
            TagsOption = tags;
            PresetsOption = presets;
            LinkOption = link;
            OnGrabOption = onGrab;
            OnDownloadOption = onDownload;
            OnUpgradeOption = onUpgrade;
            OnRenameOption = onRename;
            OnMovieAddedOption = onMovieAdded;
            OnMovieDeleteOption = onMovieDelete;
            OnMovieFileDeleteOption = onMovieFileDelete;
            OnMovieFileDeleteForUpgradeOption = onMovieFileDeleteForUpgrade;
            OnHealthIssueOption = onHealthIssue;
            IncludeHealthWarningsOption = includeHealthWarnings;
            OnHealthRestoredOption = onHealthRestored;
            OnApplicationUpdateOption = onApplicationUpdate;
            OnManualInteractionRequiredOption = onManualInteractionRequired;
            SupportsOnGrabOption = supportsOnGrab;
            SupportsOnDownloadOption = supportsOnDownload;
            SupportsOnUpgradeOption = supportsOnUpgrade;
            SupportsOnRenameOption = supportsOnRename;
            SupportsOnMovieAddedOption = supportsOnMovieAdded;
            SupportsOnMovieDeleteOption = supportsOnMovieDelete;
            SupportsOnMovieFileDeleteOption = supportsOnMovieFileDelete;
            SupportsOnMovieFileDeleteForUpgradeOption = supportsOnMovieFileDeleteForUpgrade;
            SupportsOnHealthIssueOption = supportsOnHealthIssue;
            SupportsOnHealthRestoredOption = supportsOnHealthRestored;
            SupportsOnApplicationUpdateOption = supportsOnApplicationUpdate;
            SupportsOnManualInteractionRequiredOption = supportsOnManualInteractionRequired;
            TestCommandOption = testCommand;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Fields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Field>?> FieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [JsonPropertyName("fields")]
        public List<Field>? Fields { get { return this.FieldsOption.Value; } set { this.FieldsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ImplementationName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImplementationNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ImplementationName
        /// </summary>
        [JsonPropertyName("implementationName")]
        public string? ImplementationName { get { return this.ImplementationNameOption.Value; } set { this.ImplementationNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Implementation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImplementationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Implementation
        /// </summary>
        [JsonPropertyName("implementation")]
        public string? Implementation { get { return this.ImplementationOption.Value; } set { this.ImplementationOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConfigContract
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConfigContractOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConfigContract
        /// </summary>
        [JsonPropertyName("configContract")]
        public string? ConfigContract { get { return this.ConfigContractOption.Value; } set { this.ConfigContractOption = new(value); } }

        /// <summary>
        /// Used to track the state of InfoLink
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InfoLinkOption { get; private set; }

        /// <summary>
        /// Gets or Sets InfoLink
        /// </summary>
        [JsonPropertyName("infoLink")]
        public string? InfoLink { get { return this.InfoLinkOption.Value; } set { this.InfoLinkOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ProviderMessage?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public ProviderMessage? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<int>? Tags { get { return this.TagsOption.Value; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Presets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<NotificationResource>?> PresetsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Presets
        /// </summary>
        [JsonPropertyName("presets")]
        public List<NotificationResource>? Presets { get { return this.PresetsOption.Value; } set { this.PresetsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Link
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LinkOption { get; private set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [JsonPropertyName("link")]
        public string? Link { get { return this.LinkOption.Value; } set { this.LinkOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnGrab
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnGrabOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnGrab
        /// </summary>
        [JsonPropertyName("onGrab")]
        public bool? OnGrab { get { return this.OnGrabOption.Value; } set { this.OnGrabOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnDownload
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnDownloadOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnDownload
        /// </summary>
        [JsonPropertyName("onDownload")]
        public bool? OnDownload { get { return this.OnDownloadOption.Value; } set { this.OnDownloadOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnUpgrade
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnUpgradeOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnUpgrade
        /// </summary>
        [JsonPropertyName("onUpgrade")]
        public bool? OnUpgrade { get { return this.OnUpgradeOption.Value; } set { this.OnUpgradeOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnRename
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnRenameOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnRename
        /// </summary>
        [JsonPropertyName("onRename")]
        public bool? OnRename { get { return this.OnRenameOption.Value; } set { this.OnRenameOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnMovieAdded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnMovieAddedOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnMovieAdded
        /// </summary>
        [JsonPropertyName("onMovieAdded")]
        public bool? OnMovieAdded { get { return this.OnMovieAddedOption.Value; } set { this.OnMovieAddedOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnMovieDelete
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnMovieDeleteOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnMovieDelete
        /// </summary>
        [JsonPropertyName("onMovieDelete")]
        public bool? OnMovieDelete { get { return this.OnMovieDeleteOption.Value; } set { this.OnMovieDeleteOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnMovieFileDelete
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnMovieFileDeleteOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnMovieFileDelete
        /// </summary>
        [JsonPropertyName("onMovieFileDelete")]
        public bool? OnMovieFileDelete { get { return this.OnMovieFileDeleteOption.Value; } set { this.OnMovieFileDeleteOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnMovieFileDeleteForUpgrade
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnMovieFileDeleteForUpgradeOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnMovieFileDeleteForUpgrade
        /// </summary>
        [JsonPropertyName("onMovieFileDeleteForUpgrade")]
        public bool? OnMovieFileDeleteForUpgrade { get { return this.OnMovieFileDeleteForUpgradeOption.Value; } set { this.OnMovieFileDeleteForUpgradeOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnHealthIssue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnHealthIssueOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnHealthIssue
        /// </summary>
        [JsonPropertyName("onHealthIssue")]
        public bool? OnHealthIssue { get { return this.OnHealthIssueOption.Value; } set { this.OnHealthIssueOption = new(value); } }

        /// <summary>
        /// Used to track the state of IncludeHealthWarnings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IncludeHealthWarningsOption { get; private set; }

        /// <summary>
        /// Gets or Sets IncludeHealthWarnings
        /// </summary>
        [JsonPropertyName("includeHealthWarnings")]
        public bool? IncludeHealthWarnings { get { return this.IncludeHealthWarningsOption.Value; } set { this.IncludeHealthWarningsOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnHealthRestored
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnHealthRestoredOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnHealthRestored
        /// </summary>
        [JsonPropertyName("onHealthRestored")]
        public bool? OnHealthRestored { get { return this.OnHealthRestoredOption.Value; } set { this.OnHealthRestoredOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnApplicationUpdate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnApplicationUpdateOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnApplicationUpdate
        /// </summary>
        [JsonPropertyName("onApplicationUpdate")]
        public bool? OnApplicationUpdate { get { return this.OnApplicationUpdateOption.Value; } set { this.OnApplicationUpdateOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnManualInteractionRequired
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OnManualInteractionRequiredOption { get; private set; }

        /// <summary>
        /// Gets or Sets OnManualInteractionRequired
        /// </summary>
        [JsonPropertyName("onManualInteractionRequired")]
        public bool? OnManualInteractionRequired { get { return this.OnManualInteractionRequiredOption.Value; } set { this.OnManualInteractionRequiredOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnGrab
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnGrabOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnGrab
        /// </summary>
        [JsonPropertyName("supportsOnGrab")]
        public bool? SupportsOnGrab { get { return this.SupportsOnGrabOption.Value; } set { this.SupportsOnGrabOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnDownload
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnDownloadOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnDownload
        /// </summary>
        [JsonPropertyName("supportsOnDownload")]
        public bool? SupportsOnDownload { get { return this.SupportsOnDownloadOption.Value; } set { this.SupportsOnDownloadOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnUpgrade
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnUpgradeOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnUpgrade
        /// </summary>
        [JsonPropertyName("supportsOnUpgrade")]
        public bool? SupportsOnUpgrade { get { return this.SupportsOnUpgradeOption.Value; } set { this.SupportsOnUpgradeOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnRename
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnRenameOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnRename
        /// </summary>
        [JsonPropertyName("supportsOnRename")]
        public bool? SupportsOnRename { get { return this.SupportsOnRenameOption.Value; } set { this.SupportsOnRenameOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnMovieAdded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnMovieAddedOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnMovieAdded
        /// </summary>
        [JsonPropertyName("supportsOnMovieAdded")]
        public bool? SupportsOnMovieAdded { get { return this.SupportsOnMovieAddedOption.Value; } set { this.SupportsOnMovieAddedOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnMovieDelete
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnMovieDeleteOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnMovieDelete
        /// </summary>
        [JsonPropertyName("supportsOnMovieDelete")]
        public bool? SupportsOnMovieDelete { get { return this.SupportsOnMovieDeleteOption.Value; } set { this.SupportsOnMovieDeleteOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnMovieFileDelete
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnMovieFileDeleteOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnMovieFileDelete
        /// </summary>
        [JsonPropertyName("supportsOnMovieFileDelete")]
        public bool? SupportsOnMovieFileDelete { get { return this.SupportsOnMovieFileDeleteOption.Value; } set { this.SupportsOnMovieFileDeleteOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnMovieFileDeleteForUpgrade
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnMovieFileDeleteForUpgradeOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnMovieFileDeleteForUpgrade
        /// </summary>
        [JsonPropertyName("supportsOnMovieFileDeleteForUpgrade")]
        public bool? SupportsOnMovieFileDeleteForUpgrade { get { return this.SupportsOnMovieFileDeleteForUpgradeOption.Value; } set { this.SupportsOnMovieFileDeleteForUpgradeOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnHealthIssue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnHealthIssueOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnHealthIssue
        /// </summary>
        [JsonPropertyName("supportsOnHealthIssue")]
        public bool? SupportsOnHealthIssue { get { return this.SupportsOnHealthIssueOption.Value; } set { this.SupportsOnHealthIssueOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnHealthRestored
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnHealthRestoredOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnHealthRestored
        /// </summary>
        [JsonPropertyName("supportsOnHealthRestored")]
        public bool? SupportsOnHealthRestored { get { return this.SupportsOnHealthRestoredOption.Value; } set { this.SupportsOnHealthRestoredOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnApplicationUpdate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnApplicationUpdateOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnApplicationUpdate
        /// </summary>
        [JsonPropertyName("supportsOnApplicationUpdate")]
        public bool? SupportsOnApplicationUpdate { get { return this.SupportsOnApplicationUpdateOption.Value; } set { this.SupportsOnApplicationUpdateOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportsOnManualInteractionRequired
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SupportsOnManualInteractionRequiredOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportsOnManualInteractionRequired
        /// </summary>
        [JsonPropertyName("supportsOnManualInteractionRequired")]
        public bool? SupportsOnManualInteractionRequired { get { return this.SupportsOnManualInteractionRequiredOption.Value; } set { this.SupportsOnManualInteractionRequiredOption = new(value); } }

        /// <summary>
        /// Used to track the state of TestCommand
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TestCommandOption { get; private set; }

        /// <summary>
        /// Gets or Sets TestCommand
        /// </summary>
        [JsonPropertyName("testCommand")]
        public string? TestCommand { get { return this.TestCommandOption.Value; } set { this.TestCommandOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotificationResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  ImplementationName: ").Append(ImplementationName).Append("\n");
            sb.Append("  Implementation: ").Append(Implementation).Append("\n");
            sb.Append("  ConfigContract: ").Append(ConfigContract).Append("\n");
            sb.Append("  InfoLink: ").Append(InfoLink).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Presets: ").Append(Presets).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  OnGrab: ").Append(OnGrab).Append("\n");
            sb.Append("  OnDownload: ").Append(OnDownload).Append("\n");
            sb.Append("  OnUpgrade: ").Append(OnUpgrade).Append("\n");
            sb.Append("  OnRename: ").Append(OnRename).Append("\n");
            sb.Append("  OnMovieAdded: ").Append(OnMovieAdded).Append("\n");
            sb.Append("  OnMovieDelete: ").Append(OnMovieDelete).Append("\n");
            sb.Append("  OnMovieFileDelete: ").Append(OnMovieFileDelete).Append("\n");
            sb.Append("  OnMovieFileDeleteForUpgrade: ").Append(OnMovieFileDeleteForUpgrade).Append("\n");
            sb.Append("  OnHealthIssue: ").Append(OnHealthIssue).Append("\n");
            sb.Append("  IncludeHealthWarnings: ").Append(IncludeHealthWarnings).Append("\n");
            sb.Append("  OnHealthRestored: ").Append(OnHealthRestored).Append("\n");
            sb.Append("  OnApplicationUpdate: ").Append(OnApplicationUpdate).Append("\n");
            sb.Append("  OnManualInteractionRequired: ").Append(OnManualInteractionRequired).Append("\n");
            sb.Append("  SupportsOnGrab: ").Append(SupportsOnGrab).Append("\n");
            sb.Append("  SupportsOnDownload: ").Append(SupportsOnDownload).Append("\n");
            sb.Append("  SupportsOnUpgrade: ").Append(SupportsOnUpgrade).Append("\n");
            sb.Append("  SupportsOnRename: ").Append(SupportsOnRename).Append("\n");
            sb.Append("  SupportsOnMovieAdded: ").Append(SupportsOnMovieAdded).Append("\n");
            sb.Append("  SupportsOnMovieDelete: ").Append(SupportsOnMovieDelete).Append("\n");
            sb.Append("  SupportsOnMovieFileDelete: ").Append(SupportsOnMovieFileDelete).Append("\n");
            sb.Append("  SupportsOnMovieFileDeleteForUpgrade: ").Append(SupportsOnMovieFileDeleteForUpgrade).Append("\n");
            sb.Append("  SupportsOnHealthIssue: ").Append(SupportsOnHealthIssue).Append("\n");
            sb.Append("  SupportsOnHealthRestored: ").Append(SupportsOnHealthRestored).Append("\n");
            sb.Append("  SupportsOnApplicationUpdate: ").Append(SupportsOnApplicationUpdate).Append("\n");
            sb.Append("  SupportsOnManualInteractionRequired: ").Append(SupportsOnManualInteractionRequired).Append("\n");
            sb.Append("  TestCommand: ").Append(TestCommand).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NotificationResource" />
    /// </summary>
    public partial class NotificationResourceJsonConverter : JsonConverter<NotificationResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationResourceJsonConverter" /> class.
        /// </summary>
        public NotificationResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NotificationResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NotificationResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<List<Field>?> fields = default;
            Option<string?> implementationName = default;
            Option<string?> implementation = default;
            Option<string?> configContract = default;
            Option<string?> infoLink = default;
            Option<ProviderMessage?> message = default;
            Option<List<int>?> tags = default;
            Option<List<NotificationResource>?> presets = default;
            Option<string?> link = default;
            Option<bool?> onGrab = default;
            Option<bool?> onDownload = default;
            Option<bool?> onUpgrade = default;
            Option<bool?> onRename = default;
            Option<bool?> onMovieAdded = default;
            Option<bool?> onMovieDelete = default;
            Option<bool?> onMovieFileDelete = default;
            Option<bool?> onMovieFileDeleteForUpgrade = default;
            Option<bool?> onHealthIssue = default;
            Option<bool?> includeHealthWarnings = default;
            Option<bool?> onHealthRestored = default;
            Option<bool?> onApplicationUpdate = default;
            Option<bool?> onManualInteractionRequired = default;
            Option<bool?> supportsOnGrab = default;
            Option<bool?> supportsOnDownload = default;
            Option<bool?> supportsOnUpgrade = default;
            Option<bool?> supportsOnRename = default;
            Option<bool?> supportsOnMovieAdded = default;
            Option<bool?> supportsOnMovieDelete = default;
            Option<bool?> supportsOnMovieFileDelete = default;
            Option<bool?> supportsOnMovieFileDeleteForUpgrade = default;
            Option<bool?> supportsOnHealthIssue = default;
            Option<bool?> supportsOnHealthRestored = default;
            Option<bool?> supportsOnApplicationUpdate = default;
            Option<bool?> supportsOnManualInteractionRequired = default;
            Option<string?> testCommand = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "fields":
                            fields = new Option<List<Field>?>(JsonSerializer.Deserialize<List<Field>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "implementationName":
                            implementationName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "implementation":
                            implementation = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "configContract":
                            configContract = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "infoLink":
                            infoLink = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "message":
                            message = new Option<ProviderMessage?>(JsonSerializer.Deserialize<ProviderMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "presets":
                            presets = new Option<List<NotificationResource>?>(JsonSerializer.Deserialize<List<NotificationResource>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "link":
                            link = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "onGrab":
                            onGrab = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onDownload":
                            onDownload = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onUpgrade":
                            onUpgrade = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onRename":
                            onRename = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onMovieAdded":
                            onMovieAdded = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onMovieDelete":
                            onMovieDelete = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onMovieFileDelete":
                            onMovieFileDelete = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onMovieFileDeleteForUpgrade":
                            onMovieFileDeleteForUpgrade = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onHealthIssue":
                            onHealthIssue = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "includeHealthWarnings":
                            includeHealthWarnings = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onHealthRestored":
                            onHealthRestored = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onApplicationUpdate":
                            onApplicationUpdate = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "onManualInteractionRequired":
                            onManualInteractionRequired = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnGrab":
                            supportsOnGrab = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnDownload":
                            supportsOnDownload = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnUpgrade":
                            supportsOnUpgrade = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnRename":
                            supportsOnRename = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnMovieAdded":
                            supportsOnMovieAdded = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnMovieDelete":
                            supportsOnMovieDelete = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnMovieFileDelete":
                            supportsOnMovieFileDelete = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnMovieFileDeleteForUpgrade":
                            supportsOnMovieFileDeleteForUpgrade = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnHealthIssue":
                            supportsOnHealthIssue = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnHealthRestored":
                            supportsOnHealthRestored = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnApplicationUpdate":
                            supportsOnApplicationUpdate = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "supportsOnManualInteractionRequired":
                            supportsOnManualInteractionRequired = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "testCommand":
                            testCommand = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class NotificationResource.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class NotificationResource.");

            if (onGrab.IsSet && onGrab.Value == null)
                throw new ArgumentNullException(nameof(onGrab), "Property is not nullable for class NotificationResource.");

            if (onDownload.IsSet && onDownload.Value == null)
                throw new ArgumentNullException(nameof(onDownload), "Property is not nullable for class NotificationResource.");

            if (onUpgrade.IsSet && onUpgrade.Value == null)
                throw new ArgumentNullException(nameof(onUpgrade), "Property is not nullable for class NotificationResource.");

            if (onRename.IsSet && onRename.Value == null)
                throw new ArgumentNullException(nameof(onRename), "Property is not nullable for class NotificationResource.");

            if (onMovieAdded.IsSet && onMovieAdded.Value == null)
                throw new ArgumentNullException(nameof(onMovieAdded), "Property is not nullable for class NotificationResource.");

            if (onMovieDelete.IsSet && onMovieDelete.Value == null)
                throw new ArgumentNullException(nameof(onMovieDelete), "Property is not nullable for class NotificationResource.");

            if (onMovieFileDelete.IsSet && onMovieFileDelete.Value == null)
                throw new ArgumentNullException(nameof(onMovieFileDelete), "Property is not nullable for class NotificationResource.");

            if (onMovieFileDeleteForUpgrade.IsSet && onMovieFileDeleteForUpgrade.Value == null)
                throw new ArgumentNullException(nameof(onMovieFileDeleteForUpgrade), "Property is not nullable for class NotificationResource.");

            if (onHealthIssue.IsSet && onHealthIssue.Value == null)
                throw new ArgumentNullException(nameof(onHealthIssue), "Property is not nullable for class NotificationResource.");

            if (includeHealthWarnings.IsSet && includeHealthWarnings.Value == null)
                throw new ArgumentNullException(nameof(includeHealthWarnings), "Property is not nullable for class NotificationResource.");

            if (onHealthRestored.IsSet && onHealthRestored.Value == null)
                throw new ArgumentNullException(nameof(onHealthRestored), "Property is not nullable for class NotificationResource.");

            if (onApplicationUpdate.IsSet && onApplicationUpdate.Value == null)
                throw new ArgumentNullException(nameof(onApplicationUpdate), "Property is not nullable for class NotificationResource.");

            if (onManualInteractionRequired.IsSet && onManualInteractionRequired.Value == null)
                throw new ArgumentNullException(nameof(onManualInteractionRequired), "Property is not nullable for class NotificationResource.");

            if (supportsOnGrab.IsSet && supportsOnGrab.Value == null)
                throw new ArgumentNullException(nameof(supportsOnGrab), "Property is not nullable for class NotificationResource.");

            if (supportsOnDownload.IsSet && supportsOnDownload.Value == null)
                throw new ArgumentNullException(nameof(supportsOnDownload), "Property is not nullable for class NotificationResource.");

            if (supportsOnUpgrade.IsSet && supportsOnUpgrade.Value == null)
                throw new ArgumentNullException(nameof(supportsOnUpgrade), "Property is not nullable for class NotificationResource.");

            if (supportsOnRename.IsSet && supportsOnRename.Value == null)
                throw new ArgumentNullException(nameof(supportsOnRename), "Property is not nullable for class NotificationResource.");

            if (supportsOnMovieAdded.IsSet && supportsOnMovieAdded.Value == null)
                throw new ArgumentNullException(nameof(supportsOnMovieAdded), "Property is not nullable for class NotificationResource.");

            if (supportsOnMovieDelete.IsSet && supportsOnMovieDelete.Value == null)
                throw new ArgumentNullException(nameof(supportsOnMovieDelete), "Property is not nullable for class NotificationResource.");

            if (supportsOnMovieFileDelete.IsSet && supportsOnMovieFileDelete.Value == null)
                throw new ArgumentNullException(nameof(supportsOnMovieFileDelete), "Property is not nullable for class NotificationResource.");

            if (supportsOnMovieFileDeleteForUpgrade.IsSet && supportsOnMovieFileDeleteForUpgrade.Value == null)
                throw new ArgumentNullException(nameof(supportsOnMovieFileDeleteForUpgrade), "Property is not nullable for class NotificationResource.");

            if (supportsOnHealthIssue.IsSet && supportsOnHealthIssue.Value == null)
                throw new ArgumentNullException(nameof(supportsOnHealthIssue), "Property is not nullable for class NotificationResource.");

            if (supportsOnHealthRestored.IsSet && supportsOnHealthRestored.Value == null)
                throw new ArgumentNullException(nameof(supportsOnHealthRestored), "Property is not nullable for class NotificationResource.");

            if (supportsOnApplicationUpdate.IsSet && supportsOnApplicationUpdate.Value == null)
                throw new ArgumentNullException(nameof(supportsOnApplicationUpdate), "Property is not nullable for class NotificationResource.");

            if (supportsOnManualInteractionRequired.IsSet && supportsOnManualInteractionRequired.Value == null)
                throw new ArgumentNullException(nameof(supportsOnManualInteractionRequired), "Property is not nullable for class NotificationResource.");

            return new NotificationResource(id, name, fields, implementationName, implementation, configContract, infoLink, message, tags, presets, link, onGrab, onDownload, onUpgrade, onRename, onMovieAdded, onMovieDelete, onMovieFileDelete, onMovieFileDeleteForUpgrade, onHealthIssue, includeHealthWarnings, onHealthRestored, onApplicationUpdate, onManualInteractionRequired, supportsOnGrab, supportsOnDownload, supportsOnUpgrade, supportsOnRename, supportsOnMovieAdded, supportsOnMovieDelete, supportsOnMovieFileDelete, supportsOnMovieFileDeleteForUpgrade, supportsOnHealthIssue, supportsOnHealthRestored, supportsOnApplicationUpdate, supportsOnManualInteractionRequired, testCommand);
        }

        /// <summary>
        /// Serializes a <see cref="NotificationResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notificationResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NotificationResource notificationResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, notificationResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NotificationResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notificationResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NotificationResource notificationResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (notificationResource.MessageOption.IsSet && notificationResource.Message == null)
                throw new ArgumentNullException(nameof(notificationResource.Message), "Property is required for class NotificationResource.");

            if (notificationResource.IdOption.IsSet)
                writer.WriteNumber("id", notificationResource.IdOption.Value!.Value);

            if (notificationResource.NameOption.IsSet)
                if (notificationResource.NameOption.Value != null)
                    writer.WriteString("name", notificationResource.Name);
                else
                    writer.WriteNull("name");

            if (notificationResource.FieldsOption.IsSet)
                if (notificationResource.FieldsOption.Value != null)
                {
                    writer.WritePropertyName("fields");
                    JsonSerializer.Serialize(writer, notificationResource.Fields, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("fields");
            if (notificationResource.ImplementationNameOption.IsSet)
                if (notificationResource.ImplementationNameOption.Value != null)
                    writer.WriteString("implementationName", notificationResource.ImplementationName);
                else
                    writer.WriteNull("implementationName");

            if (notificationResource.ImplementationOption.IsSet)
                if (notificationResource.ImplementationOption.Value != null)
                    writer.WriteString("implementation", notificationResource.Implementation);
                else
                    writer.WriteNull("implementation");

            if (notificationResource.ConfigContractOption.IsSet)
                if (notificationResource.ConfigContractOption.Value != null)
                    writer.WriteString("configContract", notificationResource.ConfigContract);
                else
                    writer.WriteNull("configContract");

            if (notificationResource.InfoLinkOption.IsSet)
                if (notificationResource.InfoLinkOption.Value != null)
                    writer.WriteString("infoLink", notificationResource.InfoLink);
                else
                    writer.WriteNull("infoLink");

            if (notificationResource.MessageOption.IsSet)
            {
                writer.WritePropertyName("message");
                JsonSerializer.Serialize(writer, notificationResource.Message, jsonSerializerOptions);
            }
            if (notificationResource.TagsOption.IsSet)
                if (notificationResource.TagsOption.Value != null)
                {
                    writer.WritePropertyName("tags");
                    JsonSerializer.Serialize(writer, notificationResource.Tags, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("tags");
            if (notificationResource.PresetsOption.IsSet)
                if (notificationResource.PresetsOption.Value != null)
                {
                    writer.WritePropertyName("presets");
                    JsonSerializer.Serialize(writer, notificationResource.Presets, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("presets");
            if (notificationResource.LinkOption.IsSet)
                if (notificationResource.LinkOption.Value != null)
                    writer.WriteString("link", notificationResource.Link);
                else
                    writer.WriteNull("link");

            if (notificationResource.OnGrabOption.IsSet)
                writer.WriteBoolean("onGrab", notificationResource.OnGrabOption.Value!.Value);

            if (notificationResource.OnDownloadOption.IsSet)
                writer.WriteBoolean("onDownload", notificationResource.OnDownloadOption.Value!.Value);

            if (notificationResource.OnUpgradeOption.IsSet)
                writer.WriteBoolean("onUpgrade", notificationResource.OnUpgradeOption.Value!.Value);

            if (notificationResource.OnRenameOption.IsSet)
                writer.WriteBoolean("onRename", notificationResource.OnRenameOption.Value!.Value);

            if (notificationResource.OnMovieAddedOption.IsSet)
                writer.WriteBoolean("onMovieAdded", notificationResource.OnMovieAddedOption.Value!.Value);

            if (notificationResource.OnMovieDeleteOption.IsSet)
                writer.WriteBoolean("onMovieDelete", notificationResource.OnMovieDeleteOption.Value!.Value);

            if (notificationResource.OnMovieFileDeleteOption.IsSet)
                writer.WriteBoolean("onMovieFileDelete", notificationResource.OnMovieFileDeleteOption.Value!.Value);

            if (notificationResource.OnMovieFileDeleteForUpgradeOption.IsSet)
                writer.WriteBoolean("onMovieFileDeleteForUpgrade", notificationResource.OnMovieFileDeleteForUpgradeOption.Value!.Value);

            if (notificationResource.OnHealthIssueOption.IsSet)
                writer.WriteBoolean("onHealthIssue", notificationResource.OnHealthIssueOption.Value!.Value);

            if (notificationResource.IncludeHealthWarningsOption.IsSet)
                writer.WriteBoolean("includeHealthWarnings", notificationResource.IncludeHealthWarningsOption.Value!.Value);

            if (notificationResource.OnHealthRestoredOption.IsSet)
                writer.WriteBoolean("onHealthRestored", notificationResource.OnHealthRestoredOption.Value!.Value);

            if (notificationResource.OnApplicationUpdateOption.IsSet)
                writer.WriteBoolean("onApplicationUpdate", notificationResource.OnApplicationUpdateOption.Value!.Value);

            if (notificationResource.OnManualInteractionRequiredOption.IsSet)
                writer.WriteBoolean("onManualInteractionRequired", notificationResource.OnManualInteractionRequiredOption.Value!.Value);

            if (notificationResource.SupportsOnGrabOption.IsSet)
                writer.WriteBoolean("supportsOnGrab", notificationResource.SupportsOnGrabOption.Value!.Value);

            if (notificationResource.SupportsOnDownloadOption.IsSet)
                writer.WriteBoolean("supportsOnDownload", notificationResource.SupportsOnDownloadOption.Value!.Value);

            if (notificationResource.SupportsOnUpgradeOption.IsSet)
                writer.WriteBoolean("supportsOnUpgrade", notificationResource.SupportsOnUpgradeOption.Value!.Value);

            if (notificationResource.SupportsOnRenameOption.IsSet)
                writer.WriteBoolean("supportsOnRename", notificationResource.SupportsOnRenameOption.Value!.Value);

            if (notificationResource.SupportsOnMovieAddedOption.IsSet)
                writer.WriteBoolean("supportsOnMovieAdded", notificationResource.SupportsOnMovieAddedOption.Value!.Value);

            if (notificationResource.SupportsOnMovieDeleteOption.IsSet)
                writer.WriteBoolean("supportsOnMovieDelete", notificationResource.SupportsOnMovieDeleteOption.Value!.Value);

            if (notificationResource.SupportsOnMovieFileDeleteOption.IsSet)
                writer.WriteBoolean("supportsOnMovieFileDelete", notificationResource.SupportsOnMovieFileDeleteOption.Value!.Value);

            if (notificationResource.SupportsOnMovieFileDeleteForUpgradeOption.IsSet)
                writer.WriteBoolean("supportsOnMovieFileDeleteForUpgrade", notificationResource.SupportsOnMovieFileDeleteForUpgradeOption.Value!.Value);

            if (notificationResource.SupportsOnHealthIssueOption.IsSet)
                writer.WriteBoolean("supportsOnHealthIssue", notificationResource.SupportsOnHealthIssueOption.Value!.Value);

            if (notificationResource.SupportsOnHealthRestoredOption.IsSet)
                writer.WriteBoolean("supportsOnHealthRestored", notificationResource.SupportsOnHealthRestoredOption.Value!.Value);

            if (notificationResource.SupportsOnApplicationUpdateOption.IsSet)
                writer.WriteBoolean("supportsOnApplicationUpdate", notificationResource.SupportsOnApplicationUpdateOption.Value!.Value);

            if (notificationResource.SupportsOnManualInteractionRequiredOption.IsSet)
                writer.WriteBoolean("supportsOnManualInteractionRequired", notificationResource.SupportsOnManualInteractionRequiredOption.Value!.Value);

            if (notificationResource.TestCommandOption.IsSet)
                if (notificationResource.TestCommandOption.Value != null)
                    writer.WriteString("testCommand", notificationResource.TestCommand);
                else
                    writer.WriteNull("testCommand");
        }
    }
}
