// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr3.Net.Client;

namespace Whisparr3.Net.Model
{
    /// <summary>
    /// ParseResource
    /// </summary>
    public partial class ParseResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParseResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="title">title</param>
        /// <param name="parsedMovieInfo">parsedMovieInfo</param>
        /// <param name="movie">movie</param>
        /// <param name="languages">languages</param>
        /// <param name="customFormats">customFormats</param>
        /// <param name="customFormatScore">customFormatScore</param>
        [JsonConstructor]
        public ParseResource(Option<int?> id = default, Option<string?> title = default, Option<ParsedMovieInfo?> parsedMovieInfo = default, Option<MovieResource?> movie = default, Option<List<Language>?> languages = default, Option<List<CustomFormatResource>?> customFormats = default, Option<int?> customFormatScore = default)
        {
            IdOption = id;
            TitleOption = title;
            ParsedMovieInfoOption = parsedMovieInfo;
            MovieOption = movie;
            LanguagesOption = languages;
            CustomFormatsOption = customFormats;
            CustomFormatScoreOption = customFormatScore;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption.Value; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of ParsedMovieInfo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ParsedMovieInfo?> ParsedMovieInfoOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParsedMovieInfo
        /// </summary>
        [JsonPropertyName("parsedMovieInfo")]
        public ParsedMovieInfo? ParsedMovieInfo { get { return this.ParsedMovieInfoOption.Value; } set { this.ParsedMovieInfoOption = new(value); } }

        /// <summary>
        /// Used to track the state of Movie
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MovieResource?> MovieOption { get; private set; }

        /// <summary>
        /// Gets or Sets Movie
        /// </summary>
        [JsonPropertyName("movie")]
        public MovieResource? Movie { get { return this.MovieOption.Value; } set { this.MovieOption = new(value); } }

        /// <summary>
        /// Used to track the state of Languages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Language>?> LanguagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Languages
        /// </summary>
        [JsonPropertyName("languages")]
        public List<Language>? Languages { get { return this.LanguagesOption.Value; } set { this.LanguagesOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFormats
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CustomFormatResource>?> CustomFormatsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFormats
        /// </summary>
        [JsonPropertyName("customFormats")]
        public List<CustomFormatResource>? CustomFormats { get { return this.CustomFormatsOption.Value; } set { this.CustomFormatsOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFormatScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CustomFormatScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFormatScore
        /// </summary>
        [JsonPropertyName("customFormatScore")]
        public int? CustomFormatScore { get { return this.CustomFormatScoreOption.Value; } set { this.CustomFormatScoreOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ParseResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  ParsedMovieInfo: ").Append(ParsedMovieInfo).Append("\n");
            sb.Append("  Movie: ").Append(Movie).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("  CustomFormats: ").Append(CustomFormats).Append("\n");
            sb.Append("  CustomFormatScore: ").Append(CustomFormatScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ParseResource" />
    /// </summary>
    public partial class ParseResourceJsonConverter : JsonConverter<ParseResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ParseResourceJsonConverter" /> class.
        /// </summary>
        public ParseResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ParseResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ParseResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> title = default;
            Option<ParsedMovieInfo?> parsedMovieInfo = default;
            Option<MovieResource?> movie = default;
            Option<List<Language>?> languages = default;
            Option<List<CustomFormatResource>?> customFormats = default;
            Option<int?> customFormatScore = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "parsedMovieInfo":
                            parsedMovieInfo = new Option<ParsedMovieInfo?>(JsonSerializer.Deserialize<ParsedMovieInfo>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "movie":
                            movie = new Option<MovieResource?>(JsonSerializer.Deserialize<MovieResource>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "languages":
                            languages = new Option<List<Language>?>(JsonSerializer.Deserialize<List<Language>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "customFormats":
                            customFormats = new Option<List<CustomFormatResource>?>(JsonSerializer.Deserialize<List<CustomFormatResource>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "customFormatScore":
                            customFormatScore = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ParseResource.");

            if (parsedMovieInfo.IsSet && parsedMovieInfo.Value == null)
                throw new ArgumentNullException(nameof(parsedMovieInfo), "Property is not nullable for class ParseResource.");

            if (movie.IsSet && movie.Value == null)
                throw new ArgumentNullException(nameof(movie), "Property is not nullable for class ParseResource.");

            if (customFormatScore.IsSet && customFormatScore.Value == null)
                throw new ArgumentNullException(nameof(customFormatScore), "Property is not nullable for class ParseResource.");

            return new ParseResource(id, title, parsedMovieInfo, movie, languages, customFormats, customFormatScore);
        }

        /// <summary>
        /// Serializes a <see cref="ParseResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="parseResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ParseResource parseResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, parseResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ParseResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="parseResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ParseResource parseResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (parseResource.ParsedMovieInfoOption.IsSet && parseResource.ParsedMovieInfo == null)
                throw new ArgumentNullException(nameof(parseResource.ParsedMovieInfo), "Property is required for class ParseResource.");

            if (parseResource.MovieOption.IsSet && parseResource.Movie == null)
                throw new ArgumentNullException(nameof(parseResource.Movie), "Property is required for class ParseResource.");

            if (parseResource.IdOption.IsSet)
                writer.WriteNumber("id", parseResource.IdOption.Value!.Value);

            if (parseResource.TitleOption.IsSet)
                if (parseResource.TitleOption.Value != null)
                    writer.WriteString("title", parseResource.Title);
                else
                    writer.WriteNull("title");

            if (parseResource.ParsedMovieInfoOption.IsSet)
            {
                writer.WritePropertyName("parsedMovieInfo");
                JsonSerializer.Serialize(writer, parseResource.ParsedMovieInfo, jsonSerializerOptions);
            }
            if (parseResource.MovieOption.IsSet)
            {
                writer.WritePropertyName("movie");
                JsonSerializer.Serialize(writer, parseResource.Movie, jsonSerializerOptions);
            }
            if (parseResource.LanguagesOption.IsSet)
                if (parseResource.LanguagesOption.Value != null)
                {
                    writer.WritePropertyName("languages");
                    JsonSerializer.Serialize(writer, parseResource.Languages, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("languages");
            if (parseResource.CustomFormatsOption.IsSet)
                if (parseResource.CustomFormatsOption.Value != null)
                {
                    writer.WritePropertyName("customFormats");
                    JsonSerializer.Serialize(writer, parseResource.CustomFormats, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("customFormats");
            if (parseResource.CustomFormatScoreOption.IsSet)
                writer.WriteNumber("customFormatScore", parseResource.CustomFormatScoreOption.Value!.Value);
        }
    }
}
