// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr3.Net.Client;

namespace Whisparr3.Net.Model
{
    /// <summary>
    /// TagStatisticsResource
    /// </summary>
    public partial class TagStatisticsResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TagStatisticsResource" /> class.
        /// </summary>
        /// <param name="tagId">tagId</param>
        /// <param name="label">label</param>
        /// <param name="movieCount">movieCount</param>
        /// <param name="movieFileCount">movieFileCount</param>
        /// <param name="sizeOnDisk">sizeOnDisk</param>
        [JsonConstructor]
        public TagStatisticsResource(Option<int?> tagId = default, Option<string?> label = default, Option<int?> movieCount = default, Option<int?> movieFileCount = default, Option<long?> sizeOnDisk = default)
        {
            TagIdOption = tagId;
            LabelOption = label;
            MovieCountOption = movieCount;
            MovieFileCountOption = movieFileCount;
            SizeOnDiskOption = sizeOnDisk;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TagId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TagIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TagId
        /// </summary>
        [JsonPropertyName("tagId")]
        public int? TagId { get { return this.TagIdOption.Value; } set { this.TagIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Label
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string? Label { get { return this.LabelOption.Value; } set { this.LabelOption = new(value); } }

        /// <summary>
        /// Used to track the state of MovieCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MovieCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets MovieCount
        /// </summary>
        [JsonPropertyName("movieCount")]
        public int? MovieCount { get { return this.MovieCountOption.Value; } set { this.MovieCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of MovieFileCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MovieFileCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets MovieFileCount
        /// </summary>
        [JsonPropertyName("movieFileCount")]
        public int? MovieFileCount { get { return this.MovieFileCountOption.Value; } set { this.MovieFileCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SizeOnDisk
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SizeOnDiskOption { get; private set; }

        /// <summary>
        /// Gets or Sets SizeOnDisk
        /// </summary>
        [JsonPropertyName("sizeOnDisk")]
        public long? SizeOnDisk { get { return this.SizeOnDiskOption.Value; } set { this.SizeOnDiskOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TagStatisticsResource {\n");
            sb.Append("  TagId: ").Append(TagId).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  MovieCount: ").Append(MovieCount).Append("\n");
            sb.Append("  MovieFileCount: ").Append(MovieFileCount).Append("\n");
            sb.Append("  SizeOnDisk: ").Append(SizeOnDisk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TagStatisticsResource" />
    /// </summary>
    public partial class TagStatisticsResourceJsonConverter : JsonConverter<TagStatisticsResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="TagStatisticsResourceJsonConverter" /> class.
        /// </summary>
        public TagStatisticsResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="TagStatisticsResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TagStatisticsResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> tagId = default;
            Option<string?> label = default;
            Option<int?> movieCount = default;
            Option<int?> movieFileCount = default;
            Option<long?> sizeOnDisk = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "tagId":
                            tagId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "movieCount":
                            movieCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "movieFileCount":
                            movieFileCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sizeOnDisk":
                            sizeOnDisk = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (tagId.IsSet && tagId.Value == null)
                throw new ArgumentNullException(nameof(tagId), "Property is not nullable for class TagStatisticsResource.");

            if (movieCount.IsSet && movieCount.Value == null)
                throw new ArgumentNullException(nameof(movieCount), "Property is not nullable for class TagStatisticsResource.");

            if (movieFileCount.IsSet && movieFileCount.Value == null)
                throw new ArgumentNullException(nameof(movieFileCount), "Property is not nullable for class TagStatisticsResource.");

            if (sizeOnDisk.IsSet && sizeOnDisk.Value == null)
                throw new ArgumentNullException(nameof(sizeOnDisk), "Property is not nullable for class TagStatisticsResource.");

            return new TagStatisticsResource(tagId, label, movieCount, movieFileCount, sizeOnDisk);
        }

        /// <summary>
        /// Serializes a <see cref="TagStatisticsResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tagStatisticsResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TagStatisticsResource tagStatisticsResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tagStatisticsResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TagStatisticsResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tagStatisticsResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TagStatisticsResource tagStatisticsResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tagStatisticsResource.TagIdOption.IsSet)
                writer.WriteNumber("tagId", tagStatisticsResource.TagIdOption.Value!.Value);

            if (tagStatisticsResource.LabelOption.IsSet)
                if (tagStatisticsResource.LabelOption.Value != null)
                    writer.WriteString("label", tagStatisticsResource.Label);
                else
                    writer.WriteNull("label");

            if (tagStatisticsResource.MovieCountOption.IsSet)
                writer.WriteNumber("movieCount", tagStatisticsResource.MovieCountOption.Value!.Value);

            if (tagStatisticsResource.MovieFileCountOption.IsSet)
                writer.WriteNumber("movieFileCount", tagStatisticsResource.MovieFileCountOption.Value!.Value);

            if (tagStatisticsResource.SizeOnDiskOption.IsSet)
                writer.WriteNumber("sizeOnDisk", tagStatisticsResource.SizeOnDiskOption.Value!.Value);
        }
    }
}
